
-- ***********************************************************
-- **                    Tsar Vyacheslav                    **
-- ***********************************************************

	table.insert(Distributions[1]["electronicsstore"]["counter"].items, "Tsarcraft.TCBoombox");
	table.insert(Distributions[1]["electronicsstore"]["counter"].items, 2);
	table.insert(Distributions[1]["mechanic"]["metal_shelves"].items, "Tsarcraft.TCBoombox");
	table.insert(Distributions[1]["mechanic"]["metal_shelves"].items, 2);
	table.insert(Distributions[1]["motelroomoccupied"]["other"].items, "Tsarcraft.TCBoombox");
	table.insert(Distributions[1]["motelroomoccupied"]["other"].items, 2);
	table.insert(ProceduralDistributions["list"]["MusicStoreSpeaker"].items, "Tsarcraft.TCBoombox");
	table.insert(ProceduralDistributions["list"]["MusicStoreSpeaker"].items, 5);
    table.insert(ProceduralDistributions["list"]["MusicStoreOthers"].items, "Tsarcraft.TCBoombox");
    table.insert(ProceduralDistributions["list"]["MusicStoreOthers"].items, 5);
	table.insert(ProceduralDistributions["list"]["CrateAntiqueStove"].items, "Tsarcraft.TCBoombox");
	table.insert(ProceduralDistributions["list"]["CrateAntiqueStove"].items, 5);
	table.insert(Distributions[1]["garage"]["metal_shelves"].items, "Tsarcraft.TCBoombox");
    table.insert(Distributions[1]["garage"]["metal_shelves"].items, 5);
	table.insert(Distributions[1]["garagestorage"]["other"].items, "Tsarcraft.TCBoombox");
    table.insert(Distributions[1]["garagestorage"]["other"].items, 5);

    table.insert(ProceduralDistributions["list"]["WardrobeMan"].items, "Tsarcraft.TCBoombox");
    table.insert(ProceduralDistributions["list"]["WardrobeMan"].items, 2);
    table.insert(ProceduralDistributions["list"]["WardrobeWoman"].items, "Tsarcraft.TCBoombox");
    table.insert(ProceduralDistributions["list"]["WardrobeWoman"].items, 2);
    table.insert(ProceduralDistributions["list"]["WardrobeRedneck"].items, "Tsarcraft.TCBoombox");
    table.insert(ProceduralDistributions["list"]["WardrobeRedneck"].items, 2);
	table.insert(Distributions[1]["all"]["crate"].items, "Tsarcraft.TCBoombox");
	table.insert(Distributions[1]["all"]["crate"].items, 0.5);
	table.insert(Distributions[1]["all"]["desk"].items, "Tsarcraft.TCBoombox");
	table.insert(Distributions[1]["all"]["desk"].items, 0.5);
	table.insert(Distributions[1]["garage"]["metal_shelves"].items, "Tsarcraft.TCVinylplayer");
    table.insert(Distributions[1]["garage"]["metal_shelves"].items, 3);
	table.insert(Distributions[1]["garagestorage"]["other"].items, "Tsarcraft.TCVinylplayer");
    table.insert(Distributions[1]["garagestorage"]["other"].items, 3);
	table.insert(ProceduralDistributions["list"]["CrateAntiqueStove"].items, "Tsarcraft.TCVinylplayer");
	table.insert(ProceduralDistributions["list"]["CrateAntiqueStove"].items, 3);
	table.insert(Distributions[1]["garage"]["metal_shelves"].items, "Tsarcraft.TCPianograndS_AI");
	table.insert(Distributions[1]["garage"]["metal_shelves"].items, 10);
	table.insert(Distributions[1]["garage"]["metal_shelves"].items, "Tsarcraft.TCPianograndS_BI");
	table.insert(Distributions[1]["garage"]["metal_shelves"].items, 10);
	table.insert(Distributions[1]["garage"]["metal_shelves"].items, "Tsarcraft.TCPianograndS_CI");
	table.insert(Distributions[1]["garage"]["metal_shelves"].items, 10);
	table.insert(Distributions[1]["garage"]["metal_shelves"].items, "Tsarcraft.TCPianograndS_DI");
	table.insert(Distributions[1]["garage"]["metal_shelves"].items, 10);
	table.insert(Distributions[1]["garage"]["metal_shelves"].items, "Tsarcraft.TCPianograndS_EI");
	table.insert(Distributions[1]["garage"]["metal_shelves"].items, 10);
	table.insert(Distributions[1]["garage"]["metal_shelves"].items, "Tsarcraft.TCPianograndS_FI");
	table.insert(Distributions[1]["garage"]["metal_shelves"].items, 10);
	table.insert(Distributions[1]["garage"]["metal_shelves"].items, "Tsarcraft.TCPianograndS_GI");
	table.insert(Distributions[1]["garage"]["metal_shelves"].items, 10);
	table.insert(Distributions[1]["garage"]["metal_shelves"].items, "Tsarcraft.TCPianograndS_HI");
	table.insert(Distributions[1]["garage"]["metal_shelves"].items, 10);
	table.insert(Distributions[1]["garage"]["metal_shelves"].items, "Tsarcraft.TCPianograndS_II");
	table.insert(Distributions[1]["garage"]["metal_shelves"].items, 10);
	table.insert(Distributions[1]["garagestorage"]["other"].items, "Tsarcraft.TCPianograndS_AI");
	table.insert(Distributions[1]["garagestorage"]["other"].items, 5);
	table.insert(Distributions[1]["garagestorage"]["other"].items, "Tsarcraft.TCPianograndS_BI");
	table.insert(Distributions[1]["garagestorage"]["other"].items, 5);
	table.insert(Distributions[1]["garagestorage"]["other"].items, "Tsarcraft.TCPianograndS_CI");
	table.insert(Distributions[1]["garagestorage"]["other"].items, 5);
	table.insert(Distributions[1]["garagestorage"]["other"].items, "Tsarcraft.TCPianograndS_DI");
	table.insert(Distributions[1]["garagestorage"]["other"].items, 5);
	table.insert(Distributions[1]["garagestorage"]["other"].items, "Tsarcraft.TCPianograndS_EI");
	table.insert(Distributions[1]["garagestorage"]["other"].items, 5);
	table.insert(Distributions[1]["garagestorage"]["other"].items, "Tsarcraft.TCPianograndS_FI");
	table.insert(Distributions[1]["garagestorage"]["other"].items, 5);
	table.insert(Distributions[1]["garagestorage"]["other"].items, "Tsarcraft.TCPianograndS_GI");
	table.insert(Distributions[1]["garagestorage"]["other"].items, 5);
	table.insert(Distributions[1]["garagestorage"]["other"].items, "Tsarcraft.TCPianograndS_HI");
	table.insert(Distributions[1]["garagestorage"]["other"].items, 5);
	table.insert(Distributions[1]["garagestorage"]["other"].items, "Tsarcraft.TCPianograndS_II");
	table.insert(Distributions[1]["garagestorage"]["other"].items, 5);
	table.insert(ProceduralDistributions["list"]["MusicStoreSpeaker"].items, "Tsarcraft.TCMicrophone");
	table.insert(ProceduralDistributions["list"]["MusicStoreSpeaker"].items, 1);
	table.insert(Distributions[1]["garagestorage"]["other"].items, "Tsarcraft.TCMicrophone");
	table.insert(Distributions[1]["garagestorage"]["other"].items, 0.03);
	table.insert(Distributions[1]["garagestorage"]["other"].items, "Tsarcraft.TCPianoS_AD");
	table.insert(Distributions[1]["garagestorage"]["other"].items, 8);
	table.insert(Distributions[1]["garagestorage"]["other"].items, "Tsarcraft.TCPianoS_BD");
	table.insert(Distributions[1]["garagestorage"]["other"].items, 8);
	table.insert(Distributions[1]["garagestorage"]["other"].items, "Tsarcraft.TCPianoS_CD");
	table.insert(Distributions[1]["garagestorage"]["other"].items, 8);
	table.insert(Distributions[1]["garagestorage"]["other"].items, "Tsarcraft.TCPianoS_DD");
	table.insert(Distributions[1]["garagestorage"]["other"].items, 8);
	table.insert(Distributions[1]["garagestorage"]["other"].items, "Tsarcraft.TCDrumkitS_AB");
	table.insert(Distributions[1]["garagestorage"]["other"].items, 8);
	table.insert(Distributions[1]["garagestorage"]["other"].items, "Tsarcraft.TCDrumkitS_BB");
	table.insert(Distributions[1]["garagestorage"]["other"].items, 8);
	table.insert(ProceduralDistributions["list"]["MusicStoreBass"].items, "Tsarcraft.TCBassguitar");
	table.insert(ProceduralDistributions["list"]["MusicStoreBass"].items, 8);
    table.insert(ProceduralDistributions["list"]["MusicStoreGuitar"].items, "Tsarcraft.TCBassguitar");
    table.insert(ProceduralDistributions["list"]["MusicStoreGuitar"].items, 8);

print("TSARCRAFT: Distributions[1] added. ");



