if (GlobalMusic == nil) then GlobalMusic = {} end
if (MusicPlayer == nil) then MusicPlayer = {} end
if (now_play == nil) then now_play = {} end

	GlobalMusic["AndyWilliams-ItsTheMostWonderfulTimeOfTheYear(1963)"] = "TCVinylplayer"
	GlobalMusic["BennyGoodman-ThatsAPlenty(1931)"] = "TCVinylplayer"
	GlobalMusic["BillHaley-RockAroundTheClock(1955)"] = "TCVinylplayer"
	GlobalMusic["BingCrosby-IWillBeHomeForChristmas(1943)"] = "TCVinylplayer"
	GlobalMusic["BingCrosby-WhiteChristmas(1942)"] = "TCVinylplayer"
	GlobalMusic["BingCrosby-WinterWonderland(1945)"] = "TCVinylplayer"
	GlobalMusic["BobbyDarin-BrandNewHouse(1958)"] = "TCVinylplayer"
	GlobalMusic["BobbyDarin-HallelujahILoveHerSo(1956)"] = "TCVinylplayer"
	GlobalMusic["BobbyHelms-JingleBellRock(1957)"] = "TCVinylplayer"
	GlobalMusic["BootsRandolph-YaketySax(1963)"] = "TCVinylplayer"
	GlobalMusic["BrendaLee-RockinAroundTheChristmasTree(1958)"] = "TCVinylplayer"
	GlobalMusic["DeanMartin-WalkingInAWinterWonderland(1959)"] = "TCVinylplayer"
	GlobalMusic["EarthaKitt-SantaBaby(1953)"] = "TCVinylplayer"
	GlobalMusic["ElvisPresley-BlueChristmas(1957)"] = "TCVinylplayer"
	GlobalMusic["ElvisPresley-JailhouseRock(1958)"] = "TCVinylplayer"
	GlobalMusic["EnricoCaruso-UnaFurtivaLagrima(1904)"] = "TCVinylplayer"
	GlobalMusic["GeneAutry-FrostyTheSnowMan(1951)"] = "TCVinylplayer"
	GlobalMusic["GuyMitchell-HeartacheByTheNumbers50s(1959)"] = "TCVinylplayer"
	GlobalMusic["HankWilliams-LovesickBlues(1949)"] = "TCVinylplayer"
	GlobalMusic["JohnFahey-SteelGuitarRag(1965)"] = "TCVinylplayer"
	GlobalMusic["JohnnyHorton-NorthToAlaska(1965)"] = "TCVinylplayer"
	GlobalMusic["JudyGarland-HaveYourselfAMerryLittleChristmas(1944)"] = "TCVinylplayer"
	GlobalMusic["KirstenFlagstad-DieWalkure(1938)"] = "TCVinylplayer"
	GlobalMusic["LightninHopkins-JackstropperBlues(1950)"] = "TCVinylplayer"
	GlobalMusic["MelCarter-HoldMeThrillMeKissMe(1965)"] = "TCVinylplayer"
	GlobalMusic["NatKingCole-TheChristmasSong(1961)"] = "TCVinylplayer"
	GlobalMusic["RickyNelson-TravellinMan(1961)"] = "TCVinylplayer"
	GlobalMusic["RighteousBrothers-UnchainedMelody(1965)"] = "TCVinylplayer"
	GlobalMusic["RobertJohnson-WalkingBlues(1936)"] = "TCVinylplayer"
	GlobalMusic["ThurlRavenscroft-YoureAMeanOneMrGrinch(1966)"] = "TCVinylplayer"

